package:
  name: "h2o_wave"
  version: "{{ VERSION }}"

about:
  home: https://h2o.ai/products/h2o-wave
  license: Apache License Version 2.0
  license_family: Apache
  summary: Python driver for H2O Wave Realtime Apps

requirements:
  build:
    - python={{ python_version }}
    - pip
    - wheel
    - Click
    - httpx==0.16.1
    - uvicorn==0.12.2
    - starlette==0.13.8

  run:
    - python={{ python_version }}
    - Click
    - httpx==0.16.1
    - uvicorn==0.12.2
    - starlette==0.13.8

source:
  path: ..

build:
  script: python setup.py install
  string: py{{ python_version | replace(".", "") }}