[App]
Name = "ai.h2o.wave.university"
Version = "1.0.0"
Title = "Wave University"
Description = "Interactive Wave learning experience."
LongDescription = "README-cloud.md"
Tags = ["APP_DEV"]

[Runtime]
Module = "h2o_wave_university.university"
RoutingMode = "BASE_URL"
RuntimeVersion = "deb11_py310_wlatest"

[[Env]]
Name = "H2O_WAVE_PUBLIC_DIR"
Value = "/assets/@../../app/h2o_wave_university/static/"