{{ if and .Values.import.auth.oidc.usernamePassword.enabled (not .Values.import.auth.oidc.usernamePassword.existingSecret) -}}

{{- $secretName := include "university.import.auth.oidc.usernamePassword.secretName" .  }}
{{- $sec := lookup "v1" "Secret" .Release.Namespace $secretName }}

{{- $username := get (coalesce $sec.data dict) .Values.import.auth.oidc.usernamePassword.usernameKey | b64dec }}
{{- $username = .Values.import.auth.oidc.usernamePassword.username | default $username }}

{{- $password := get (coalesce $sec.data dict) .Values.import.auth.oidc.usernamePassword.passwordKey | b64dec }}
{{- $password = .Values.import.auth.oidc.usernamePassword.password | default $password }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  labels:
    {{- include "university.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.import.auth.oidc.usernamePassword.usernameKey }}: {{ $username | b64enc | quote }}
  {{ .Values.import.auth.oidc.usernamePassword.passwordKey }}: {{ $password | b64enc | quote }}

{{- end -}}
