name: Release Generated Helm Chart

on:
  workflow_call:
    inputs:
      build-version:
        type: string
        description: The version of the application/image to be pushed
        required: true

jobs:
  retrieve-metadata:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get App Version
        id: get-build-version
        run: |
          echo "VERSION=${{ inputs.build-version }}" >> "$GITHUB_OUTPUT"

  release-helm-chart:
    needs: retrieve-metadata
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    uses: ./.github/workflows/wave-bundle-helm-release.yaml
    with:
      build-version: ${{ inputs.build-version }}
      helm-chart-artifact: wave-bundle-helm
      wave-app-name: university
