name: Release Wave

on: push

jobs:
  ci-test:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
      - run: make
      - name: Unit Test
      - run: make test-ui-ci
