name: Release Wave

on: push

jobs:
  ci-test:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Build
      - uses: actions/checkout@v2
      - run:
          make
      - name: Unit Test
      - run:
        make test-ui-ci
