name: Release Wave

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: "1.0.0"
  TAG: "v1.0.0"

jobs:


  create-bundle:
    name: Create Wave Bundle
    runs-on: ubuntu-latest

    outputs:
      build-version: ${{ env.VERSION }}

    steps:
      - uses: actions/checkout@v3

      - name: Download H2O CLI
        working-directory: ./py/apps/tour
        run: mkdir -p .bin && curl -o .bin/h2o https://h2oai-cloud-release.s3.amazonaws.com/releases/ai/h2o/h2o-cloud/latest/cli/linux-amd64/h2o

      - name: Change permissions
        working-directory: ./py/apps/tour
        run: chmod +x .bin/h2o

      - name: Set version
        working-directory: ./py/apps/tour
        run: sed -i -r -e "s/\{\{VERSION\}\}/${{ env.VERSION }}/g" app.toml

      - name: Get App Version
        id: get-build-version
        run: |
          echo "VERSION=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"

      - name: Make the folder structure
        run: |
          find py/apps/tour -type f -name '*.toml' -exec sed -i -e "s/{{VERSION}}/${{ env.VERSION }}/g" {} \;
          find py/apps/tour -type f -name 'requirements.txt' -exec sed -i -e "s/{{VERSION}}/${{ env.VERSION }}/g" {} \;
          rsync -a py/examples py/apps/tour --exclude "*.idea*" --exclude "*__pycache__*" --exclude "*.mypy_cache*" --exclude "dist" --exclude "build"
          cp tools/vscode-extension/base-snippets.json py/apps/tour/examples
          cp tools/vscode-extension/component-snippets.json py/apps/tour/examples
          cp tools/vscode-extension/server/utils.py py/apps/tour/examples/tour_autocomplete_utils.py
          cp tools/vscode-extension/server/parser.py py/apps/tour/examples/tour_autocomplete_parser.py
          sed -i -r -e "s#^@app\(('|\")(.*)('|\")(.*)#@app\('/'\4#" py/apps/tour/examples/tour.py 

      - name: Make air-gapped bundle
        working-directory: ./py/apps/tour
        run: |
          .bin/h2o bundle \
            --docker-base-image 524466471676.dkr.ecr.us-east-1.amazonaws.com/q8s/launcher:v0.31.0-310 \
            --docker-use-buildkit \
            --generate-helm-charts \
            --helm-chart-version ${{ env.VERSION }} \
            --helm-chart-name tour \
            --helm-app-bundle-image-repo 524466471676.dkr.ecr.us-east-1.amazonaws.com/h2oai/tour-bundle \
            --helm-app-runtime-image-repo 524466471676.dkr.ecr.us-east-1.amazonaws.com/h2oai/tour \
            --generate-dockerfile

      - uses: actions/upload-artifact@v3
        with:
          name: wave-bundle
          path: |
            ./py/apps/tour/*.Dockerfile
            ./py/apps/tour/*.wave

      - uses: actions/upload-artifact@v3
        with:
          name: wave-bundle-helm
          path: py/apps/tour/helm/

  build-and-publish:
    needs: create-bundle
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    uses: ./.github/workflows/wave-bundle-docker-build-publish.yaml
    with:
      build-version: ${{ needs.create-bundle.outputs.build-version }}
      bundle-artifact: wave-bundle
      wave-app-name: tour
