name: Wave Bundle

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: "0.0.1"
  TAG: "0.0.1"

jobs:
  bundle:
    name: Create Wave Bundle
    working-directory: ./university
    uses: ./.github/workflows/wave-bundle.yaml

  publish:
    needs: bundle
    name: Build and Publish
    working-directory: ./university
    uses: ./.github/workflows/wave-publish.yaml

  helm-publish:
    needs: bundle
    name: Build and Publish Helm Chart
    working-directory: ./university
    uses: ./.github/workflows/helm-release.yaml
