name: Release Helm Chart

on:
  workflow_call:
    inputs:
      build-version:
        type: string
        description: The version of the application
        required: true
      helm-version:
        type: string
        description: The version of the Helm Chart to be pushed. If not provided `build-version` will be used.
        required: false
      helm-chart-artifact:
        type: string
        description: The name of the artifact containing the generated Helm chart
        required: true

jobs:
  helm:
    name: Helm Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3

      - name: Download Wave bundle and Dockerfile
        uses: actions/download-artifact@v3
        id: helm-chart-download
        with:
          name: ${{ inputs.helm-chart-artifact }}
          path: helm/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::524466471676:role/workflows-library-wave-bundling-github-actions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: "Ensure ECR Repository"
        # Tires to describe the repository and if it fails, creates it
        run: |
          aws ecr describe-repositories \
            --repository-names charts/${{ github.event.repository.name }} 2>/dev/null ||
          aws ecr create-repository \
            --repository-name charts/${{ github.event.repository.name }} \
            --image-tag-mutability IMMUTABLE \
            --tag \
              Key=GithubRepo,Value=github.com/h2oai/${{ github.event.repository.name }} \
              Key=ManagedBy,Value=GitHubActions \
              Key=CreatedByWorkflow,Value=${{ github.workflow_ref }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ github.token }}

      - name: Helm Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | helm registry login --username AWS --password-stdin \
            524466471676.dkr.ecr.us-east-1.amazonaws.com

      - name: Locate Chart.yaml
        id: locate-chart-dir
        run: |
          echo "PATH=$(dirname $(find ${{ steps.helm-chart-download.outputs.download-path }} -name Chart.yaml))" >> "$GITHUB_OUTPUT"

      - name: Package Helm Chart
        run: |
          helm package \
            ${{ steps.locate-chart-dir.outputs.PATH }} \
            --version ${{ inputs.helm-version || inputs.build-version }} \
            --app-version ${{ inputs.build-version }} \
            --dependency-update

      - name: Locate Helm package
        id: locate-helm-package
        run: |
          echo "PATH=$(find . -name *-${{ inputs.build-version }}.tgz -type f -exec basename {} \; | tr -d '[:space:]')" >> "$GITHUB_OUTPUT"

      - name: Push Helm Chart to ECR
        run: |
          helm push ${{ steps.locate-helm-package.outputs.PATH }} oci://524466471676.dkr.ecr.us-east-1.amazonaws.com/charts
