name: Wave Bundle

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: "0.0.1"
  TAG: "v0.0.1"

jobs:
  bundle:
    name: Create Wave Bundle
    uses: ./.github/workflows/wave-bundle.yaml
    with:
      build-version: ${{ env.VERSION }}

  publish:
    needs: bundle
    name: Build and Publish
    uses: ./.github/workflows/wave-publish.yaml

  helm-publish:
    needs: bundle
    name: Build and Publish Helm Chart
    uses: ./.github/workflows/helm-release.yaml
