name: Wave Bundle

on:
  workflow_call:
    inputs:
      build-version:
        type: string
        description: The version of the application/image to be pushed
        required: true

jobs:
  bundle:
    name: Create Wave Bundle
    uses: ./.github/workflows/wave-bundle-university.yaml
    with:
      build-version: ${{ inputs.build-version }}

  publish:
    needs: bundle
    name: Build and Publish
    uses: ./.github/workflows/wave-publish-university.yaml
    with:
      build-version: ${{ inputs.build-version }}

  helm-publish:
    needs: bundle
    name: Build and Publish Helm Chart
    uses: ./.github/workflows/helm-release-university.yaml
    with:
      build-version: ${{ inputs.build-version }}
